version: '3'
services:
  # Bot service
  bot:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - redis  # Ensure the bot service starts after the Redis service
    networks:
      - bot_network

  # Redis service
  redis:
    image: redis:latest  # Use the latest Redis image from Docker Hub
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    networks:
      - bot_network

networks:
  bot_network:
